---
- name: get the aplication package > build and packge > deploy to docker container
  hosts: webserver
  become: true
  vars_files:
    - proj_vars.yml
    - sudo_pass.yml
  tasks:
    - name: create the project folder
      file:
        name: "{{ proj_dir }}"
        state: directory
    - name: clone the repository using git
      git:
        repo: "{{ rep_link }}"
        dest: "{{ trg_path }}"
        force: yes
    - name: build the code using maven
      command:
        chdir: "{{ trg_path }}"
        cmd: mvn package
    - name: Copy the build artifact from the target directory to the project directory
      copy:
        src: "{{ trg_path }}/target/{{ artf }}"
        dest: "{{ trg_path }}"
        remote_src: yes
    - name: remove the cloned docker file becuase the cloned ropo has one
      file:
        path: "{{ trg_path }}/dockerfile"
        state: absent
    - name: Create the docker file
      template:
        src: dockerfile.j2
        dest: "{{ trg_path }}/dockerfile"
      notify: Build-the-docker-image
  handlers:    
    - name: Build-the-docker-image
      command:
        cmd: docker build -t {{ dok_img }} "{{ trg_path }}"
      notify: Run-into-Container

    - name: Run-into-Container
      command: " docker run -d -P {{ dok_img }}"
